# Generated by Django 3.2.7 on 2021-10-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211001_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagarticlem2m',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t1', to='articles.tags'),
        ),
    ]
