# Generated by Django 3.2.7 on 2021-10-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tagarticlem2m_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagarticlem2m',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t1', to='articles.article'),
        ),
    ]
